apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../../base/

helmCharts:
- name: console-plugin-nvidia-gpu
  version: 0.2.5
  valuesFile: values.yaml
  releaseName: console-plugin-nvidia-gpu-0.2.5
